### ISSUE TITLE
erreur bank js

### ISSUE THREAD

**Issue by DARKAOFF** [idev-co/banking-system#3]
![image](https://user-images.githubusercontent.com/427770/165698642-c4c64764-8195-455c-92ba-91c9de146732.png)

**Comment by spacevx** [comment]
Hey this error happen when you restart the script, I didn't say it in the readme but you can't restart the script in game, start the script in the cfg and be sure that you put the sql file in ur database

**Comment by DARKAOFF** [comment]
so I restarted the server and I have the same problem, I just modified the config and the colors of the css

**Comment by spacevx** [comment]
Work well for me, the ressource need to be started **before** you join the server, or you did something wrong in your edits.

If you need more help, you can go on my discord, i'm assuming ur are french, go here => https://github.com/idev-co/banking-system/tree/esx-french and join the discord (at the bottom)
